// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Clause struct {
	Var1 *Variable `json:"var1"`
	Var2 *Variable `json:"var2"`
	Var3 *Variable `json:"var3"`
}

type NewClause struct {
	Var1 *NewVariable `json:"var1"`
	Var2 *NewVariable `json:"var2"`
	Var3 *NewVariable `json:"var3"`
}

type NewJob struct {
	Name    string       `json:"name"`
	Clauses []*NewClause `json:"clauses"`
}

type NewVariable struct {
	Negated bool   `json:"negated"`
	Name    string `json:"name"`
}

type SolvedVariable struct {
	Name  string `json:"name"`
	Value bool   `json:"value"`
}

type Variable struct {
	Negated bool   `json:"negated"`
	Name    string `json:"name"`
}
